### ISSUE TITLE
Controls not destroyed when app is closed

### ISSUE THREAD

**Issue by ingageco** [ingageco/capacitor-music-controls-plugin#13]
One observation with the **android-13-style** branch of this plugin is that the controls are not destroyed when closing the application. This happens in 2 instances:

A.
- Open your application
- Play some music for some time (media controls are created)
- Close the application
==> The media controls persist.

B.
- Open the application
- Play some music and stop the music (media controls are created, no active streams)
- Put the application to the background
- Wait for e.g. 15 minutes
==> The system will close the application, but the media controls are still visible.

This reproduces on Android 12 as well as 13.

_Originally posted by @NorthFred in https://github.com/ingageco/capacitor-music-controls-plugin-v3/issues/11#issuecomment-1600303748_

**Comment by ingageco** [comment]
@NorthFred Can you update and see if you still get this behavior?

**Comment by NorthFred** [comment]
@ingageco The situation has improved. When the music is playing and the application is closed, then the music controls are dismissed as well. However, when the music is stopped and the application is closed, the media controls remain visible.
So strangely enough, it works as long as music is playing...

**Comment by NorthFred** [comment]
@ingageco Also, I think I am ready to start using this in production - there are no showstoppers at least. Are you ready to merge `android-13-style` branch to the main branch?

**Comment by ingageco** [comment]
> @ingageco The situation has improved. When the music is playing and the application is closed, then the music controls are dismissed as well. However, when the music is stopped and the application is closed, the media controls remain visible. So strangely enough, it works as long as music is playing... (same for Android 12 and 13).

I get the same experience when the music is paused and app is closed. I just need to figure out how to detect this and why it is different from when the music is playing. 

I'll merge asap!

**Comment by ingageco** [comment]
@NorthFred shipped to NPM / main branch as 1.1.0. prob should have done it as a 2.0 just bc of breaking changes. 

BUT - i was able to hook into the app lifecycle and kill the notification. Check 1.1.0 and see if the one unresolved issue you had is now resolved. 

Again - having a baby tomorrow, so you may not hear back for a bit - but thank you!

**Comment by NorthFred** [comment]
@ingageco Thank you for everything! Issue is now resolved and verified. I will release my apps to production and keep an eye on the crash logs. I'm so happy this plugin is now up-to-date for API level 33.
Wishing you and your family all the best!

**Comment by NorthFred** [comment]
@ingageco You can close this one - I am not able to do it...
