### ISSUE TITLE
Any plan to support duration progress bar on Android?

### ISSUE THREAD

**Issue by Amoyens1s** [ingageco/capacitor-music-controls-plugin#17]
now duration is ios only, progress bar not showing in android

**Comment by ingageco** [comment]
@Amoyens1s Frankly, i'm not certain that we ever supported the duration / progress for android in this plugin (remember, we ported this over from an older plugin, and just kept same features). You can see in the example that duration/elapse is iOS only. We'll have to see if and how we can support this for Android in the near future.

**Comment by ingageco** [comment]
I find my way around Android / Java dev for this plugin but i am no expert. I'll make another attempt at adding it in the next couple of weeks.

**Comment by gamble4846** [comment]
any updates on this? @ingageco

**Comment by ingageco** [comment]
I'm open to a PR that resolves this.

Currently working my way into the React Native world, so I don't have plans to push this plugin further than my own needs. But I'll happily review PRs and merge.
