### ISSUE TITLE
Capacitor 4 : Type com.ingageco.capacitormusiccontrols.capacitormusiccontrolsplugin.BuildConfig Error in Android Studio

### ISSUE THREAD

**Issue by lohnsonok** [ingageco/capacitor-music-controls-plugin#18]
Type com.ingageco.capacitormusiccontrols.capacitormusiccontrolsplugin.BuildConfig is defined multiple times: /app-mobile/node_modules/capacitor-music-controls-plugin/android/build/.transforms/2268045407ebc5e3db2404fc87605523/transformed/debug/com/ingageco/capacitormusiccontrols/capacitormusiccontrolsplugin/BuildConfig.dex, /app-mobile/node_modules/capacitor-music-controls-plugin-v3/android/build/.transforms/76f530be7517eda3c0da8f93012e23a9/transformed/debug/com/ingageco/capacitormusiccontrols/capacitormusiccontrolsplugin/BuildConfig.dex

**Comment by ingageco** [comment]
@lohnsonok PR welcome to fix
