### ISSUE TITLE
Service.startForeground() issue

### ISSUE THREAD

**Issue by eusouluiz** [ingageco/capacitor-music-controls-plugin#19]
While trying to use the plugin I've faced the error below:
> Reason: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{d65ee0f u0 de.example.app/com.ingageco.capacitormusiccontrols.MusicControlsNotificationKiller}

Apparently, after a quick research:
> The issue you are facing is related to the way foreground services are handled in Android. Starting from Android 8.0 (API level 26) and above, there are restrictions on how services can be started and brought to the foreground to improve user experience and prevent abuse by background services. When you call Context.startForegroundService(), you are indicating that you want to start a foreground service, but you must follow it up with a call to Service.startForeground() within a certain time frame to promote the service to foreground status officially. If you fail to do so, the system will terminate the service and raise the error you are encountering.
> 
> To fix this issue, you need to make sure you call Service.startForeground() within your service's onCreate() method or shortly after starting the service.

**Comment by ingageco** [comment]
@eusouluiz Thank you for reporting & doing the initial research - it really helps. I'll look into this asap!

**Comment by MayeulChassagnard** [comment]
Hi, I'm experiencing the exactly same issue here. Anyone found a work around by any chance ?
