### ISSUE TITLE
Problem with stream type

### ISSUE THREAD

**Issue by idesignzone** [ingageco/capacitor-music-controls-plugin#20]
I am trying to stream remote MP3 file.
URL looks like `http://webside.com/file.mp3`
Controller never shows up.

Audio manager shows a warning in console: 
Use of stream types is deprecated for operations other than volume control. See the [documentation](https://developer.android.com/reference/android/media/AudioManager) of requestAudioFocus() for what to use instead with android.media.AudioAttributes to qualify your playback use case".

![image](https://github.com/ingageco/capacitor-music-controls-plugin-v3/assets/3501211/8931e9c9-01a7-49cc-9d4c-51d70e71b183)

Android 12
"@capacitor/core": "^5.2.3",
"capacitor-music-controls-plugin-v3": "^1.1.2",

**Comment by ingageco** [comment]
@idesignzone This plugin is tested up to Capacitor 4, but not beyond (yet). Thank you for reporting this

**Comment by idesignzone** [comment]
For those using Capacitor 3+ I had success with [capacitor-media-session](https://github.com/jofr/capacitor-media-session).

**Comment by ingageco** [comment]
@idesignzone This plugin supports Capacitor 3 & 4

**Comment by ingageco** [comment]
The newest version of this plugin now supports Capacitor 5
