### ISSUE TITLE
IOS not showing track string and icon image but showing in android

### ISSUE THREAD

**Issue by saddam0710** [ingageco/capacitor-music-controls-plugin#21]
My code is

CapacitorMusicControls['create']({
      track       : '1610am CHHA',    // optional, default : ''
      artist      : '1610am CHHA',           // optional, default : ''
      album       : '',     // optional, default: ''
      cover       : 'assets/logo.png',

**Comment by ingageco** [comment]
Please review the instructions and ensure you are correctly calling the create function. The posted code is not correct for creating the controls
