### ISSUE TITLE
Does nothing on iOS

### ISSUE THREAD

**Issue by Ralle** [ingageco/capacitor-music-controls-plugin#25]
Hello,

I am trying to use this on Capacitor 6 on iOS for SoundWheel. My app is a NextJS app, so I am using a React `useEffect` to trigger `"capacitor-music-controls-plugin"`. Like so:

```typescript
  useEffect(() => {
    (async () => {
      const { CapacitorMusicControls } = await import(
        "capacitor-music-controls-plugin"
      );
      await CapacitorMusicControls.create({
        track: "Time is Running Out", // optional, default : ''
        artist: "Muse", // optional, default : ''
        album: "Absolution", // optional, default: ''
        // cover: "albums/absolution.jpg", // optional, default : nothing
        // cover can be a local path (use fullpath 'file:///storage/emulated/...',
        // or only 'my_image.jpg' if my_image.jpg is in the www folder of your app)
        // or a remote url ('http://...', 'https://...', 'ftp://...')

        // hide previous/next/close buttons:
        hasPrev: false, // show previous button, optional, default: true
        hasNext: false, // show next button, optional, default: true
        hasClose: true, // show close button, optional, default: false

        // iOS only, all optional
        duration: 60, // default: 0
        elapsed: 10, // default: 0
        hasSkipForward: true, // default: false. true value overrides hasNext.
        hasSkipBackward: true, // default: false. true value overrides hasPrev.
        skipForwardInterval: 15, // default: 15.
        skipBackwardInterval: 15, // default: 15.
        hasScrubbing: false, // default: false. Enable scrubbing from control center progress bar

        // Android only, all optional
        isPlaying: true, // default : true
        dismissable: true, // default : false
        // text displayed in the status bar when the notification (and the ticker) are updated
        ticker: 'Now playing "Time is Running Out"',
        // All icons default to their built-in android equivalents
        // The supplied drawable name, e.g. 'media_play', is the name of a drawable found under android/res/drawable* folders
        playIcon: "media_play",
        pauseIcon: "media_pause",
        prevIcon: "media_prev",
        nextIcon: "media_next",
        closeIcon: "media_close",
        notificationIcon: "notification",
      });
    })();
  }, [state.code]);
```
But it doesn't do anything.

When `state.code` changes, my app uses an `<audio />` tag to play the sound and calls this module. But all I see on the lock screen is the contents of the `<title>` tag because of the default behavior when playing audio. Before playing any audio, it still does not show.

I guarantee that the code is being run, because I was using the `debugger;` statement inside. I believe I've done everything right and this doesn't work on iOS at all. But that makes no sense. Please help :)

I'm seeing this in the console:
<img width="816" alt="image" src="https://github.com/user-attachments/assets/b0fa4f85-b439-4984-aa7a-de6aecf641bc">

Also, the reason why I am not importing it at the top is because it would be imported in the server (SSR) and that causes crashes.

**Comment by ingageco** [comment]
Try playing the audio first, then setting up controls. AFAIK, audio must already be playing before the controls can be instantiated.

**Comment by Ralle** [comment]
Oh! I didn’t think of that. Thank you, will try that tomorrow.

**Comment by Ralle** [comment]
You were right. You have to start playing audio first and the MediaSession will attach itself to said playback it seems. Thank you.
